[package]
name = "v9_worker"
version = "0.1.0"
authors = ["Gregor Peach <gregorpeach@gmail.com>"]
edition = "2018"

[dependencies]
failure = { version = "0.1.5", features = ["derive"]}
flexi_logger = "0.14.3"
hyper = "0.12.35"
lazy_static = "1.4.0"
log = "0.4.8"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
