[package]
name = "v9_worker"
version = "0.1.0"
authors = ["Gregor Peach <gregorpeach@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.35"
lazy_static = "1.4.0"
log = "0.4.8"
simple_logger = "1.3.0"