version: 2.1
orbs:
  rust: glotrade/rust@0.1.3
workflows:
  build:
    jobs:
      - rust/format:
          toolchain: 'stable'
      - rust/clippy:
          toolchain: 'stable'
      - rust/test:
          toolchain: 'stable'

